alias: EV Charger Grid Excess Tracking
description: Adjust EV target amperage dynamically based on grid meter excess power
triggers:
  - minutes: /1
    trigger: time_pattern
conditions:
  - condition: time
    after: "04:00:00"
    before: "22:00:00"
actions:
  - variables:
      voltage: "{{ states('sensor.feyree_ev_charger_voltage') | float(240) }}"
      ev_current_draw: "{{ states('sensor.feyree_ev_charger_current') | float(0) }}"
      buffer: 500
  - variables:
      available_power: "{{ states('sensor.available_power_average')|int(0) + buffer }}"
      minimum_cutoff_power: "{{4*voltage}}"
      minimum_turnon_power: "{{8*voltage}}"
  - variables:
      target_step: "{{ (available_power/voltage) | float(0) | int(0) }}"
      safe_target_step: "{{ target_step | clamp(8,32) }}"
  - action: input_number.set_value
    target:
      entity_id: input_number.ev_charger_amp_target
    data:
      value: "{{safe_target_step}}"
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ available_power < minimum_cutoff_power }}"
        sequence:
          - action: select.select_option
            target:
              entity_id: select.feyree_ev_charger_charging
            data:
              option: "off"
      - conditions:
          - condition: template
            value_template: "{{ available_power > minimum_turnon_power }}"
        sequence:
          - action: select.select_option
            target:
              entity_id: select.feyree_ev_charger_charging
            data:
              option: "on"
mode: single
